In [1]:
import numpy as np
from scipy import linalg
import math

A = np.array([[3388.7, 6205.5, -3582.8, -9206.1], [0, 1796.3, -4950.8, 8103.8], [0, 6.4641, -3.73205, 1]])

In [21]:
def decompose_P(P):
    u, s, vh  = np.linalg.svd(A, full_matrices=True)
    lastCol = vh[-1]
    C = lastCol / lastCol[-1]
    M = A[:,0:3]
    k, r = linalg.rq(M)
    k = k / k[2,2]
    fix_t = np.eye(3)
    if(k[0,0] < 0):
        fix_t[0,0] = -1
    if(k[1,1] < 0):
        fix_t[1,1] = -1
    K = np.dot(k, fix_t)
    R = np.dot(fix_t, r)
    if(np.linalg.det(R) < 0):
        R = -R
    T = -R * C[0:-1]
    return (C, T, R, K)

In [22]:
C, T, R, K = decompose_P(A)
print("Camera matrix\n", C)
print("Rotation matrix\n", R)
print("Camera Calibration\n", K)

Camera matrix
 [3.0000295  0.99977872 1.99961673 1.        ]
Rotation matrix
 [[ 1.          0.          0.        ]
 [ 0.         -0.50000001 -0.8660254 ]
 [ 0.          0.8660254  -0.50000001]]
Camera Calibration
 [[4.53999824e+02 6.12435716e-03 9.59997967e+02]
 [0.00000000e+00 4.54089387e+02 5.40057285e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
