In [1]:
import numpy as np

In [3]:
principle_point = np.array([[1002.07, 425.696]]).T
camera_center = np.array([[0, 0.35, 0.4]]).T
# pitched downward 15 degrees is rotation about the x-axis
alpha = (-105/ 180) * np.pi
R = np.array([[1, 0, 0], [0, np.cos(alpha), np.sin(alpha)], [0, -np.sin(alpha), np.cos(alpha)]])
print(R)

[[ 1.          0.          0.        ]
 [ 0.         -0.25881905 -0.96592583]
 [ 0.          0.96592583 -0.25881905]]


In [11]:
R_C = -np.dot(R, camera_center)
print(R_C)

[[-0.        ]
 [ 0.476957  ]
 [-0.23454642]]


In [16]:
K = np.array([[796.607, 0, 1002.07], [0, 793.91, 425.696],[0, 0, 1]]).T
t = np.hstack((R, R_C))
projection_matrix = np.dot(K, t)
print(projection_matrix)

[[ 796.607         0.            0.            0.        ]
 [   0.         -205.4790281  -766.85817275  378.66092893]
 [1002.07       -109.2123064  -411.44957959  202.80413908]]


In [30]:
H = np.array([[796.607, 0, 0], [0, -205.4790281, 378.66092893], [1002.07,-109.2123064, 202.80413908]])
print(H)

[[ 796.607         0.            0.        ]
 [   0.         -205.4790281   378.66092893]
 [1002.07       -109.2123064   202.80413908]]


In [34]:
# inspecting the image using GIMP and finding the camera coordinate 
# for bottom right of the black chair
black_chair_coordinate = np.array([[1430, 670, 1]]).T
inv_H = np.linalg.inv(H)
chair_ground_coordinate = np.dot(inv_H, black_chair_coordinate)
print(chair_ground_coordinate)

[[ 1.79511353e+00]
 [-2.57159667e+03]
 [-1.39369854e+03]]
