In [2]:
import numpy as np
import math

A = np.array([[3388.7, 6205.5, -3582.8, -9206.1], [0, 1796.3, -4950.8, 8103.8], [0, 6.4641, -3.73205, 1]])


In [3]:
from scipy import linalg
r, q = linalg.rq(A)
print('r', r);
print('--------------')
print('q', q)

r [[ 0.00000000e+00  5.35856615e+03  9.18130013e+03 -5.87960439e+03]
 [ 0.00000000e+00  0.00000000e+00 -8.22734781e+03 -5.07143341e+03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -7.53078920e+00]]
--------------
q [[ 0.77465073  0.25815723  0.51632977  0.25821437]
 [ 0.63238932 -0.31623192 -0.63248259 -0.31630191]
 [-0.          0.31076802  0.29627269 -0.90313107]
 [-0.         -0.85835625  0.49557223 -0.13278821]]


In [4]:
u, s, vh  = np.linalg.svd(A, full_matrices=True)
lastCol = vh[-1]
C = lastCol / lastCol[-1]
print('Camera coordinate', C)

Camera coordinate [3.0000295  0.99977872 1.99961673 1.        ]


In [6]:
M = A[:,0:3]
k, r = linalg.rq(M)
k = k / k[2,2]
fix_t = np.eye(3)
print(k)
if(k[0,0] < 0):
    k[0,0] = 0
if(k[0,1] < 0):
    k[0,1] = 0
# k = k * fix_t

print(k)
print(r)

[[ 4.53999824e+02 -6.12435716e-03  9.59997967e+02]
 [ 0.00000000e+00 -4.54089387e+02  5.40057285e+02]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[ 453.99982383    0.          959.99796668]
 [   0.         -454.0893873   540.05728529]
 [   0.            0.            1.        ]]
[[ 1.          0.          0.        ]
 [-0.          0.50000001  0.8660254 ]
 [ 0.          0.8660254  -0.50000001]]


In [21]:
alpha = (-120 * np.pi / 180)
C = np.array([[3,1,2]]).T
R = np.array([[1, 0, 0], [0, np.cos(alpha), np.sin(alpha)], [0, -np.sin(alpha), np.cos(alpha)]])
t = -np.dot(R, C)
k = np.array([[454, 0, 960], [0, 454, 540], [0, 0, 1]])
R_RC = np.hstack((R, t))
P = np.dot(k, R_RC)
print(P)
X = np.array([[1200, 700, 1]]).T
Pp = np.dot(np.linalg.pinv(P), X)
# all points in lamda can be described by X(lambda) = pinv(P)X + lambda.C, we want lambda such that P+ X [3] + lambda * 2 = 0
print(-Pp[2] * 2 /2 )

[[ 4.54000000e+02  8.31384388e+02 -4.80000000e+02 -1.23338439e+03]
 [ 0.00000000e+00  2.40653718e+02 -6.63175533e+02  1.08569735e+03]
 [ 0.00000000e+00  8.66025404e-01 -5.00000000e-01  1.33974596e-01]]
[0.89391421]
